### ISSUE TITLE
Model can not converge

### ISSUE THREAD

**Issue by VJJJJJJ1** [jishengpeng/WavTokenizer#52]
hi, I try to train wavtokenizer on ljspeech and libritts respectively, but the loss seems can not converge. I did'n change any code, just change the following configuration:
```
data:
  class_path: decoder.dataset.VocosDataModule
  init_args:
    train_params:
      filelist_path: ./WavTokenizer-main/data/LJSPEECH/train.txt
      sampling_rate: 24000
      num_samples: 24000
      batch_size: 16
      num_workers: 8

    val_params:
      filelist_path: ./WavTokenizer-main/data/LJSPEECH/val.txt
      sampling_rate: 24000
      num_samples: 24000
      batch_size: 5 
      num_workers: 8
```
and can see loss as the pic, Is my configuration incorrect? Or still need to continue to wait? thanks for reply!
![image](https://github.com/user-attachments/assets/97fb2d3e-9a31-4e6f-ae9c-d1dd252e9cf6)
